// <auto-generated />
namespace BlexDigital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class proyectonombre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proyectonombre));
        
        string IMigrationMetadata.Id
        {
            get { return "202107140721005_proyecto-nombre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
